---
title: "Homework 2"
author: '[Group name and member names]'
date: ""
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, error=TRUE)
```

## Task 3

```{r constructor}
myclass <- function(x){
  stopifnot(length(x) == 4)
  structure(x, class = "myarray")
}

myprint <- function(x){
  UseMethod("myprint")
}
myprint.default <- function(x){
  cat("no print")
}

myprint.myarray <- function(x){
  cat(x)
}
```

```{r validator}
mycheck <- function(x){
  #stopifnot(is.integer(x)==TRUE)
  #stopifnot(sum(x)>0)
  if(is.integer(x)==TRUE & sum(x) >0){
    return ("all good")
  }
  else{
    return ("not good")
  }
 
}
```

```{r helper}
myhelper <- function(x){
  if(length(x)==4 & mycheck(x) == "all good"){
    myclass(x)
  }
  else{
    newx <- abs(round(x[1:4], 0))
    myclass(newx)
  
  }
}
```

```{r examples}
myclass(1:4)
mycheck(c(1.1,1.2,1.3,2))
myhelper(c(1.1,1.2,1.3,2))
myhelper(c(1.1,1.2,1.3,2,2.1,2.2))
myhelper(1:4)
myprint(myclass(1:4))
myprint(1:4)
```

## Task 4

Please include your write-up here...

